INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "SSDGXBD"
  NUM_LABELED: 84
  AUX_NAME1: "xbd"
  AUX_NAME2: "aux_xbd"

MODEL:
  BACKBONE:
    NAME: "resnet34"
    PRETRAINED: True