INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "SSDGPACS"
  NUM_LABELED: 210
  AUX_NAME1: "images"
  AUX_NAME2: "aux_images"

MODEL:
  BACKBONE:
    NAME: "resnet34"
    PRETRAINED: True